services:
  application:
    hostname: ${APPLICATION}
    container_name: ${APPLICATION}
    build: .
    restart: always
    ports:
      - "${APPLICATION_PORT}:${APPLICATION_PORT}"
    environment:
      JAVA_OPTS: |
        -Dspring.profiles.active=docker
        -Dserver.port=${APPLICATION_PORT}
        -Dmanagement.zipkin.tracing.endpoint=http://jaeger:9411/api/v2/spans
    healthcheck:
      test: curl localhost:${APPLICATION_PORT}/actuator/health || exit 1
      interval: 20s
      timeout: 60s
      retries: 3

networks:
  default:
    external: true
    name: ${DOCKER_NETWORK}